[project]
name = "gssex"
version = "1.0.0"
description = "Genesis Save State Extractor"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pillow>=12.1.0",
    "pyside6>=6.10.1",
]

[dependency-groups]
dev = [
    "nuitka>=2.8.10",
]
